# Generated by Django 5.2.3 on 2026-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
