# Generated by Django 5.2.10 on 2026-02-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('lot', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.produits')),
            ],
        ),
    ]
