# Generated by Django 5.2.10 on 2026-02-02 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrée', 'Entrée'), ('sortie', 'Sortie')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.stock')),
            ],
        ),
    ]
