# Generated by Django 5.2.10 on 2026-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='unite',
            field=models.CharField(choices=[('flacons', 'PIECES'), ('flacons', 'PIECES')], default='none', max_length=100),
        ),
    ]
