# Generated by Django 5.2.10 on 2026-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_produits_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='unite',
            field=models.CharField(choices=[('flacons', 'Flacons'), ('pieces', 'Pieces')], default='none', max_length=100),
        ),
    ]
