# Generated by Django 5.2.10 on 2026-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_produits_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='destination',
            field=models.CharField(choices=[('enfant', 'Enfant'), ('adulte', 'Adulte')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='produits',
            name='usage',
            field=models.CharField(choices=[('injectable', 'Injectable'), ('sirop', 'Sirop'), ('suppositoire', 'Suppositoire'), ('applicable', 'Applicable'), ('comprimes', 'Comprimes'), ('ampoules', 'Ampoules')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='produits',
            name='date_ajout',
            field=models.DateField(auto_now_add=True),
        ),
    ]
