# Generated by Django 5.2.10 on 2026-02-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_produits_destination_produits_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='usage',
            field=models.CharField(choices=[('injectable', 'Injectable'), ('sirop', 'Sirop'), ('suppositoire', 'Suppositoire'), ('usage externe', 'Usage externe'), ('comprimes', 'Comprimes'), ('ampoules', 'Ampoules')], default='none', max_length=100),
        ),
    ]
