# Generated by Django 5.2.10 on 2026-02-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_produits_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='forme',
            field=models.CharField(choices=[('comprime', 'Comprime'), ('gelule', 'Gelule'), ('sirop', 'Sirop'), ('suppositoire', 'Suppositoire'), ('suspension buvable', 'Suspension buvable'), ('lyophilisat oral', 'Lyophilisat oral'), ('injection', 'Injection'), ('appareil electronique', 'Appareil electronique'), ('appareil mecanique', 'Appareil mecanique'), ('poudre', 'Poudre'), ('tybe/pot de creme', 'Tybe/pot de creme')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='produits',
            name='mode',
            field=models.CharField(choices=[('sur ordonance', 'Sur ordonance'), ('vente libre', 'Vente libre')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='produits',
            name='type',
            field=models.CharField(choices=[('medicaments', 'Medicaments'), ('dispositifs medicales', 'Dispositifs medicales'), ('parapharmacie', 'Parapharmacie')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='produits',
            name='unite',
            field=models.CharField(choices=[('flacons', 'Flacons'), ('pieces', 'Pieces'), ('boites', 'Boites'), ('tubes', 'Tubes')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='produits',
            name='usage',
            field=models.CharField(choices=[('orale', 'Orale'), ('injectable', 'Injectable'), ('utilisation externe', 'Utilisation externe'), ('cutané', 'Cutané'), ('rectale', 'Rectale')], default='none', max_length=100),
        ),
    ]
