# Generated by Django 5.2.10 on 2026-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_produits_forme_produits_mode_produits_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='destination',
            field=models.CharField(choices=[('enfant', 'Enfant'), ('adulte', 'Adulte'), ('adultes/enfants', 'Adultes/enfants')], default='none', max_length=100),
        ),
    ]
