# Generated by Django 5.2.11 on 2026-02-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_alter_produits_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prix',
        ),
    ]
