# Generated by Django 5.1.4 on 2025-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compteUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('password_confirm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='vente',
            new_name='produitVente',
        ),
        migrations.AddField(
            model_name='customer',
            name='adresse',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.DeleteModel(
            name='facture_Client',
        ),
    ]
