# Generated by Django 5.1.4 on 2026-01-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_facture_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.customer')),
            ],
        ),
        migrations.CreateModel(
            name='elementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produits')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.facture')),
            ],
        ),
        migrations.DeleteModel(
            name='facture_Client',
        ),
    ]
