# Generated by Django 5.1.4 on 2026-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_facture_elementfacture_delete_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ventes',
            field=models.ManyToManyField(related_name='factures', to='Produits.produitvente'),
        ),
        migrations.DeleteModel(
            name='elementFacture',
        ),
    ]
